# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the file I want to run
      run: |
        python src/your_package_name/your_package_name.py
    - name: Build wheel
      run: |
        python -m pip install --upgrade build
        python -m build
    - name: Install wheel
      run: |
        pip install "dist/your_package_name-1.0.0-py3-none-any.whl"
    - name: Try to run it (__init__.py only)
      run: |
        your_package_name_init
    - name: Try to run it (the actual main)
      run: |
        your_package_name
